export const SELECT_SHELVES_ORDER = "SELECT_SHELVES_ORDER";
export const CREATE_SHELVES_ORDER = "CREATE_SHELVES_ORDER";
export const ADD_SHELVE_TO_ORDER = "ADD_SHELVE_TO_ORDER";
export const UPDATE_SHELVES_ORDER_LIST = "UPDATE_SHELVES_ORDER_LIST";
export const UPDATE_SELECT_SHELVES_ORDER = "UPDATE_SELECT_SHELVES_ORDER";
