export const CREATE_SHELVE_ITEM = "CREATE_SHELVE_ITEM";
export const DELETE_SHELVE_ITEM = "DELETE_SHELVE_ITEM";
export const GET_FOCUS_SHELVE_ITEM = "GET_FOCUS_SHELVE_ITEM";
export const GET_SELECT_SHELVES = "GET_SELECT_SHELVES";
export const DELETE_SHELVES_GLOBAL = "DELETE_SHELVES_GLOBAL";
export const ADD_CARD_TO_SELECT_SHELVE = "ADD_CARD_TO_SELECT_SHELVE";
export const UPDATE_SELECT_SHELVE_CARD_ORDER =
  "UPDATE_SELECT_SHELVE_CARD_ORDER";
